# Generated by Django 4.2.1 on 2023-05-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_rename_author_id_ad_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
